org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.51-beta
neo_version_range=[26.3.0.51-beta,)
java_version=25

mod_id=helion
mod_name=Helion
mod_version=0.1
mod_group_id=com.aryston.helion
mod_license=LGPL-3.0-only
mod_authors=Can
mod_url=https://github.com/lureidcom/Helion
